# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

def installed_pods
    pod 'Alamofire', '~> 3.4'
    pod 'AlamofireObjectMapper', '~> 3.0'
    pod 'RealmSwift'
    pod 'ObjectMapper', '~> 1.3'
    pod 'PureLayout'
    pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift'
    pod 'SCLAlertView'
    pod 'GoogleMaps', '~> 1.13'
    pod 'CocoaLumberjack/Swift'
    pod "PKHUD"
end


target 'CANNavApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CANNavApp
  installed_pods

  target 'CANNavAppTests' do
    inherit! :search_paths
    # Pods for testing
    installed_pods
    pod 'Nimble'
  end

end
